### ISSUE TITLE
[2pts] Implement methods

### ISSUE THREAD

**Issue by Bavon101** [ahangarha/Ruby-Capstone#10]
- Implement methods:
    - [x] add_item method in the Genre class
        - should take an instance of the Item class as an input
        - [x] should add the input item to the collection of items
        - [x] should add self as a property of the item object (by using the correct setter from the item object)
    - [x] can_be_archived?() in the MusicAlbum class
        - [x] should override the method from the parent class
         - [x] should return true if parent's method returns true AND if on_spotify equals true
         - [x] otherwise, it should return false

**Comment by Bavon101** [comment]
The above methods were implemented during class creation in both  `MusicAlbum` and `Genre` classes. It can be closed after the final review of both classes.

**Comment by ahangarha** [comment]
Yes.

We need to only implement things required for the the given task.

In this case I think these two issues could be merged into one issue. But not a big issue. We are good to go.

So I think this issue can be closed now.

Thanks
